# Generated by Django 4.0.4 on 2022-09-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15)),
                ('owner_location', models.CharField(default='', max_length=30)),
                ('owner_img', models.ImageField(default='', upload_to='images')),
                ('contact', models.CharField(default='', max_length=11)),
                ('map', models.CharField(default='', max_length=5000)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=10)),
                ('no_of_room', models.IntegerField(default=0)),
                ('pub_date', models.CharField(default='', max_length=30)),
                ('image1', models.ImageField(default='', upload_to='images')),
                ('image2', models.ImageField(default='', upload_to='images')),
                ('image3', models.ImageField(default='', upload_to='images')),
                ('image4', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
