# Generated by Django 4.0.4 on 2022-10-04 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_id', models.CharField(default='', max_length=35)),
                ('username', models.CharField(default='', max_length=15)),
                ('category', models.CharField(default='', max_length=50)),
                ('price', models.CharField(default='', max_length=10)),
                ('no_of_room', models.IntegerField(default=0)),
                ('pub_date', models.CharField(default='', max_length=30)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('postal_code', models.IntegerField(default=0)),
                ('description', models.CharField(default='', max_length=20000)),
                ('division', models.CharField(default='', max_length=20)),
                ('district', models.CharField(default='', max_length=20)),
                ('thana', models.CharField(default='', max_length=20)),
                ('union', models.CharField(default='', max_length=20)),
                ('image1', models.ImageField(default='', upload_to='images')),
                ('image2', models.ImageField(default='', upload_to='images')),
                ('image3', models.ImageField(default='', upload_to='images')),
                ('image4', models.ImageField(default='', upload_to='images')),
                ('value', models.CharField(default='avail', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=15, null=True)),
                ('fname', models.CharField(default='not entered', max_length=20, null=True)),
                ('lname', models.CharField(default='not entered', max_length=20, null=True)),
                ('address', models.CharField(default='not entered', max_length=20, null=True)),
                ('email', models.CharField(default='not entered', max_length=40, null=True)),
                ('phone', models.BigIntegerField(default='', null=True)),
                ('gender', models.CharField(default='', max_length=10, null=True)),
                ('owner_image', models.ImageField(default='not entered', null=True, upload_to='images')),
            ],
        ),
    ]
