# Generated by Django 4.0.4 on 2022-09-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(default='not entered', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.CharField(default='not entered', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fname',
            field=models.CharField(default='not entered', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lname',
            field=models.CharField(default='not entered', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='owner_image',
            field=models.ImageField(default='not entered', null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='', max_length=15, null=True),
        ),
    ]
